// Generated by gencpp from file nisa_pkg/DikdortgenAlan.msg
// DO NOT EDIT!


#ifndef NISA_PKG_MESSAGE_DIKDORTGENALAN_H
#define NISA_PKG_MESSAGE_DIKDORTGENALAN_H

#include <ros/service_traits.h>


#include <nisa_pkg/DikdortgenAlanRequest.h>
#include <nisa_pkg/DikdortgenAlanResponse.h>


namespace nisa_pkg
{

struct DikdortgenAlan
{

typedef DikdortgenAlanRequest Request;
typedef DikdortgenAlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DikdortgenAlan
} // namespace nisa_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nisa_pkg::DikdortgenAlan > {
  static const char* value()
  {
    return "6313128f6dfa3023a00d78cf460d102c";
  }

  static const char* value(const ::nisa_pkg::DikdortgenAlan&) { return value(); }
};

template<>
struct DataType< ::nisa_pkg::DikdortgenAlan > {
  static const char* value()
  {
    return "nisa_pkg/DikdortgenAlan";
  }

  static const char* value(const ::nisa_pkg::DikdortgenAlan&) { return value(); }
};


// service_traits::MD5Sum< ::nisa_pkg::DikdortgenAlanRequest> should match
// service_traits::MD5Sum< ::nisa_pkg::DikdortgenAlan >
template<>
struct MD5Sum< ::nisa_pkg::DikdortgenAlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nisa_pkg::DikdortgenAlan >::value();
  }
  static const char* value(const ::nisa_pkg::DikdortgenAlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nisa_pkg::DikdortgenAlanRequest> should match
// service_traits::DataType< ::nisa_pkg::DikdortgenAlan >
template<>
struct DataType< ::nisa_pkg::DikdortgenAlanRequest>
{
  static const char* value()
  {
    return DataType< ::nisa_pkg::DikdortgenAlan >::value();
  }
  static const char* value(const ::nisa_pkg::DikdortgenAlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nisa_pkg::DikdortgenAlanResponse> should match
// service_traits::MD5Sum< ::nisa_pkg::DikdortgenAlan >
template<>
struct MD5Sum< ::nisa_pkg::DikdortgenAlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nisa_pkg::DikdortgenAlan >::value();
  }
  static const char* value(const ::nisa_pkg::DikdortgenAlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nisa_pkg::DikdortgenAlanResponse> should match
// service_traits::DataType< ::nisa_pkg::DikdortgenAlan >
template<>
struct DataType< ::nisa_pkg::DikdortgenAlanResponse>
{
  static const char* value()
  {
    return DataType< ::nisa_pkg::DikdortgenAlan >::value();
  }
  static const char* value(const ::nisa_pkg::DikdortgenAlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NISA_PKG_MESSAGE_DIKDORTGENALAN_H
