// Generated by gencpp from file nisa_pkg/DikdortgenAlanResponse.msg
// DO NOT EDIT!


#ifndef NISA_PKG_MESSAGE_DIKDORTGENALANRESPONSE_H
#define NISA_PKG_MESSAGE_DIKDORTGENALANRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nisa_pkg
{
template <class ContainerAllocator>
struct DikdortgenAlanResponse_
{
  typedef DikdortgenAlanResponse_<ContainerAllocator> Type;

  DikdortgenAlanResponse_()
    : area(0.0)  {
    }
  DikdortgenAlanResponse_(const ContainerAllocator& _alloc)
    : area(0.0)  {
  (void)_alloc;
    }



   typedef double _area_type;
  _area_type area;





  typedef boost::shared_ptr< ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DikdortgenAlanResponse_

typedef ::nisa_pkg::DikdortgenAlanResponse_<std::allocator<void> > DikdortgenAlanResponse;

typedef boost::shared_ptr< ::nisa_pkg::DikdortgenAlanResponse > DikdortgenAlanResponsePtr;
typedef boost::shared_ptr< ::nisa_pkg::DikdortgenAlanResponse const> DikdortgenAlanResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator1> & lhs, const ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator2> & rhs)
{
  return lhs.area == rhs.area;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator1> & lhs, const ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nisa_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "502b7bd5115b3b4f57d03446f9208d12";
  }

  static const char* value(const ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x502b7bd5115b3b4fULL;
  static const uint64_t static_value2 = 0x57d03446f9208d12ULL;
};

template<class ContainerAllocator>
struct DataType< ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nisa_pkg/DikdortgenAlanResponse";
  }

  static const char* value(const ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 area\n"
"\n"
"\n"
;
  }

  static const char* value(const ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.area);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DikdortgenAlanResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nisa_pkg::DikdortgenAlanResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "area: ";
    Printer<double>::stream(s, indent + "  ", v.area);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NISA_PKG_MESSAGE_DIKDORTGENALANRESPONSE_H
