// Generated by gencpp from file nisa_pkg/DikdortgenAlanRequest.msg
// DO NOT EDIT!


#ifndef NISA_PKG_MESSAGE_DIKDORTGENALANREQUEST_H
#define NISA_PKG_MESSAGE_DIKDORTGENALANREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nisa_pkg
{
template <class ContainerAllocator>
struct DikdortgenAlanRequest_
{
  typedef DikdortgenAlanRequest_<ContainerAllocator> Type;

  DikdortgenAlanRequest_()
    : width(0.0)
    , height(0.0)  {
    }
  DikdortgenAlanRequest_(const ContainerAllocator& _alloc)
    : width(0.0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef double _width_type;
  _width_type width;

   typedef double _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DikdortgenAlanRequest_

typedef ::nisa_pkg::DikdortgenAlanRequest_<std::allocator<void> > DikdortgenAlanRequest;

typedef boost::shared_ptr< ::nisa_pkg::DikdortgenAlanRequest > DikdortgenAlanRequestPtr;
typedef boost::shared_ptr< ::nisa_pkg::DikdortgenAlanRequest const> DikdortgenAlanRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator1> & lhs, const ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator2> & rhs)
{
  return lhs.width == rhs.width &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator1> & lhs, const ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nisa_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f86522e647336fb10b55359fe003f673";
  }

  static const char* value(const ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf86522e647336fb1ULL;
  static const uint64_t static_value2 = 0x0b55359fe003f673ULL;
};

template<class ContainerAllocator>
struct DataType< ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nisa_pkg/DikdortgenAlanRequest";
  }

  static const char* value(const ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 width\n"
"float64 height\n"
;
  }

  static const char* value(const ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DikdortgenAlanRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nisa_pkg::DikdortgenAlanRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NISA_PKG_MESSAGE_DIKDORTGENALANREQUEST_H
